"""add last_login_at

Revision ID: 28e1a32d43ca
Revises:
Create Date: 2026-03-03 09:34:13.460958

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "28e1a32d43ca"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("last_login_at")

    # ### end Alembic commands ###
