"""changed estimated_quantity from nullable true to false

Revision ID: 4d46083ad324
Revises: 3f9dc4d5bbb2
Create Date: 2026-04-25 19:25:53.132999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d46083ad324'
down_revision = '3f9dc4d5bbb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('estimated_value',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('estimated_value',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
