"""add raffle_id and ticket_id to messages

Revision ID: 53a782c55ab4
Revises: 08d0137fb0a0
Create Date: 2026-07-06 13:34:35.363612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a782c55ab4'
down_revision = '08d0137fb0a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raffle_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ticket_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'raffles', ['raffle_id'], ['id'])
        batch_op.create_foreign_key(None, 'tickets', ['ticket_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ticket_id')
        batch_op.drop_column('raffle_id')

    # ### end Alembic commands ###
