"""add prize contestation tables

Revision ID: 69ff605045d5
Revises: b2c3d4e5f6a7
Create Date: 2026-07-24 10:31:50.936347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ff605045d5'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prize_contestations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prize_delivery_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('damaged', 'not_as_described', 'wrong_item', 'not_received', name='contestation_reason'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'dismissed', name='contestation_status'), nullable=False),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prize_delivery_id'], ['prize_deliveries.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prize_contestation_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prize_contestation_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['prize_contestation_id'], ['prize_contestations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prize_contestation_images')
    op.drop_table('prize_contestations')
    # ### end Alembic commands ###
