"""add product_images table

Revision ID: 9260a2c69196
Revises: 4dc46d7a83a2
Create Date: 2026-04-24 10:25:29.269530

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9260a2c69196"
down_revision = "e8e42ff5d02e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_images")
    # ### end Alembic commands ###
