"""Create raffle entity

Revision ID: f82a14d2d9f0
Revises: 28e1a32d43ca
Create Date: 2026-04-08 12:04:32.900535

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f82a14d2d9f0"
down_revision = "28e1a32d43ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raffles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "active", "completed", "cancelled", name="raffle_status"),
            nullable=False,
        ),
        sa.Column("ticket_price", sa.Integer(), nullable=False),
        sa.Column("minimum_required_tickets", sa.Integer(), nullable=False),
        sa.Column("maximum_tickets_per_user", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("raffles")
    # ### end Alembic commands ###
