"""add prize delivery tables

Revision ID: fa6d098142bf
Revises: b1c2d3e4f5a6
Create Date: 2026-07-20 11:23:13.417135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6d098142bf'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prize_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.Column('winner_user_id', sa.Integer(), nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.Column('tracking_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending_address', 'waiting_for_shipment', 'prize_sent', 'prize_delivered', 'prize_accepted', 'contested', 'delivery_failed', name='prize_delivery_status'), nullable=False),
    sa.Column('pickup_name', sa.String(length=100), nullable=False),
    sa.Column('pickup_address', sa.String(length=255), nullable=True),
    sa.Column('pickup_country', sa.String(length=50), nullable=True),
    sa.Column('pickup_phone', sa.String(length=20), nullable=True),
    sa.Column('pickup_email', sa.String(length=100), nullable=False),
    sa.Column('delivery_name', sa.String(length=100), nullable=False),
    sa.Column('delivery_address', sa.String(length=255), nullable=True),
    sa.Column('delivery_country', sa.String(length=50), nullable=True),
    sa.Column('delivery_phone', sa.String(length=20), nullable=True),
    sa.Column('delivery_email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.ForeignKeyConstraint(['winner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prize_delivery_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prize_delivery_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('from_status', sa.Enum('pending_address', 'waiting_for_shipment', 'prize_sent', 'prize_delivered', 'prize_accepted', 'contested', 'delivery_failed', name='prize_delivery_status'), nullable=True),
    sa.Column('to_status', sa.Enum('pending_address', 'waiting_for_shipment', 'prize_sent', 'prize_delivered', 'prize_accepted', 'contested', 'delivery_failed', name='prize_delivery_status'), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prize_delivery_id'], ['prize_deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prize_delivery_logs')
    op.drop_table('prize_deliveries')
    # ### end Alembic commands ###
